name: momichat

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: momichat_api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - chromadb
    restart: unless-stopped

  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: momichat_bot
    env_file:
      - .env
    environment:
      - FASTAPI_INTERNAL_URL=http://api:8080/api/v1/webhooks/chat/process_message
    depends_on:
      - api
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: momichat_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: momichat
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: momichat_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:latest
    container_name: momichat_chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  chroma_data:
